# Generated by Django 2.0.4 on 2018-04-21 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip_number', models.CharField(max_length=10)),
                ('result_from_MF', models.CharField(max_length=128)),
            ],
        ),
    ]
