# Generated by Django 2.0.4 on 2018-04-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NIP_checker_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NIP_base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip_base_number', models.CharField(max_length=10)),
            ],
        ),
    ]
