# Generated by Django 2.0.4 on 2018-04-22 07:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('NIP_checker_app', '0002_nip_base'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NIP_base',
        ),
        migrations.AddField(
            model_name='nip',
            name='check_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
