# Generated by Django 2.0.4 on 2018-04-22 08:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('NIP_checker_app', '0003_auto_20180422_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='nip',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nip',
            name='check_date',
            field=models.DateTimeField(),
        ),
    ]
