# Generated by Django 2.0.4 on 2018-04-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NIP_checker_app', '0004_auto_20180422_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nip',
            name='check_date',
            field=models.DateTimeField(null=True),
        ),
    ]
