# Generated by Django 2.0.4 on 2018-04-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NIP_checker_app', '0006_auto_20180422_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nip',
            name='add_date',
            field=models.DateTimeField(null=True),
        ),
    ]
